### ISSUE TITLE
slideToggle replacement

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/fh-components#14]

**Comment by SaFrMo** [comment]
@drewbaker @jrobson153 @lwaldner I think this is simple enough not to make into a standalone component - it'd just be something like:

```
<button @click="opened = !opened">Click to toggle!</button>

<transition name="slide-left">
  <h2 v-if="opened">Opened!</h2>
</transition>
```

I'm marking it complete - feel free to reopen if y'all think otherwise!

**Comment by johndigital** [comment]
I actually added this component in this recent commit: https://github.com/funkhaus/fh-components/commit/c337b7d5088a18fab12871246a75b503fc72e412

It's just a proxy for velocity slideToggle, the benefit of having it in js hooks rather than pure css is that the height of the element doesn't need to be hardcoded.
