### ISSUE TITLE
split-text without wrapper?

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#21]
Is it possible to have `split-text` without a wrapping element? Sometimes I need an icon inside a H2 title tag.

If it needs to have a wrapper, can we add a slot to it? This is not as good (because sometimes I need the icon before/after the text), but it would help.

**Comment by drewbaker** [comment]
I would say ideally it doesn't have a wrapper by default. You know how I feel about wrappers (and rappers for that matter)!

**Comment by johndigital** [comment]
I don’t think we’ll be able to take the wrapper out, since the whole point of this component it to render a loop of elements. Even with a render function, vue still needs a single element to be the root of the component.

But in general you should be able to use the props provided to do what you’re trying to. The ‘pieces’ prop will allow you to specify which part of the title you want, so one option would be to use 2 split-text elements to make individual parts of the title and put the icon wherever you need it.

You can also specify what element you want the wrapper to be with the wrapper prop and what elements the individual pieces should be wrapped in as well using the element prop. Maybe you could use some combination of those to get the markup you want, using ‘h2’ as the wrapper for instance since you’re going to use one anyway.

The slot may be a good improvement, though I’m not sure where the best place to put it would be. The only other thing we could do beyond that is to omit the wrapper only when a single piece is being targeted rather than a loop of all pieces. This would obviously be a super marginal improvement though.

**Comment by SaFrMo** [comment]
I agree with using the props like @jrobson153 mentioned - alternately, if I wanted an icon inside the title tag like you mentioned, @drewbaker, I'd probably do this:

```
<h2 class="title">
    <svg-image src="icon.svg"/>
    <split-text :text="$store.getters.post.title" class="split-wrap"/>
</h2>
```

This does make a little more HTML in the end result, but I think it's worth it for the readable .vue template and consistent styling.

Speaking of consistent styling, I think that's a good reason for always including a wrapper - I'd want to be sure I could do

```
.title .split-wrap span { ... }
```

in the CSS for the above example and get the same result no matter what the line length.

**Comment by drewbaker** [comment]
Thanks guys, but I have an idea: How about we have a slot, and then a prop to set if the slot is before or after the text? Like this:

```
    <split-text :text="$store.getters.post.title" class="split-wrap" slot-location="before">
         <svg-image src="something.svg"/>
    </split-text>
```

Then we could set `slot-location="after"` if we wanted the icon after the text.

This would mean we'd have no unnecessary HTML!

**Comment by SaFrMo** [comment]
Added `before` and `after` slots in 3422947, as well as tests and documentation
