### ISSUE TITLE
Split-text enhancement: Fallbacks

### ISSUE THREAD

**Issue by lwaldner** [funkhaus/fh-components#24]
If splitting text on html entity for hyphen results in list of length 1 fallback to splitting on unicode hyphen and if we get the same result fallback on splitting on " - ". 

If you want to use split text in a say a meta box WP will always use a unicode hyphen rather than an html entity

**Comment by SaFrMo** [comment]
Good idea! I added this in 02e9417. If you pass an array to the `separator` prop, it'll find the first string in that array that splits the text successfully and use that; otherwise, it'll return the full string like normal. Behavior with `separator` set to a string doesn't change.

Feel free to reopen if there are any issues!

**Comment by SaFrMo** [comment]
(I should clarify that the behavior you described @lwaldner won't happen out of the box with this change - you'll need to set the `separator` prop to `[' &#8211; ', ' - ']`.)
