### ISSUE TITLE
video-stage: Force resize calculation

### ISSUE THREAD

**Issue by lwaldner** [funkhaus/fh-components#28]
Their are times when fit-to-parent won't be able to calculate the correct size of the iframe before it loads. We need a way to call resize on the element after it loads

**Comment by SaFrMo** [comment]
Looking into this, it seems like the non-hackiest way (which still feels pretty hacky) is to use `$refs` to call the `sizeVideo` method. For example:

```
<template>
  <video-stage ref="stage" src="video.com"/>
</template>

<script>
export default {
  mounted(){
    this.$refs.stage.sizeVideo()
  }
}
</script>
```

You can do this with the component as it's currently written, but that doesn't feel great. The Vue way to communicate from parent to child seems to be with the parent changing the child's props, but since no props are actually changing, there's no non-hacky way to do it that I can see.

The other alternative is making the `video-stage` component watch its own `getBoundingClientRect()` dimensions. That should eliminate these kind of bugs, but it doesn't give the programmer the ability to force the stage to resize and it'll be pretty expensive.

@johndigital, any thoughts on this or better solutions?

**Comment by SaFrMo** [comment]
The answer above is probably going to be the best way to make this happen - using the `sizeVideo` method in combination with the [`waitFor` mixin](https://github.com/funkhaus/fh-components#waitfor) will be the best guarantee that the area sizes correctly. Closing for now, but definitely reopen if it becomes an issue in the future or we find a better way!
