### ISSUE TITLE
responsive-image auto handles image video URLs

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#34]
It would be nice if `responsive-image` would auto detect that the image object had the video url meta on it, and displayed the video (default to size cover and auto play/loop I'd think). We'd want to be able to tell it to ignore the video to, as sometimes you have a grid where you don't want the video, but then on a detail page for the same post you'd want the video.

**Comment by johndigital** [comment]
I actually thought we already had it built this way, but looks like there was a bug!

This is now implemented in https://github.com/funkhaus/fh-components/commit/095fedf6c0395c0cc053560376ae425f16862d26. You'll have to make sure you also have the latest version of Rest Easy, which is `1.41` since rest easy was not serializing meta of images by default.

**Comment by johndigital** [comment]
Also, you can force the component to not recognize the video by passing `:video-src="false"`
