### ISSUE TITLE
"Scroll to" component

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#41]
So with the help of John and Sander, I made this component that we'd use all the time. Its a thing you can click to scroll the window to a named element.

You use it like this:
```
<scroll-to scroll-target="bottom-panel">
    <svg-image src="arrow-down.svg"/>
</scroll-to>

<div ref="bottom-panel"></div>
```

And when you click that component, it will scroll the window to the target. 

Here is the code. It has easing and speed props too.

```
<template>

    <div class="scroll-to" @click="scrollTo">
        <slot></slot>
    </div>

</template>

<script>
        props: {
            scrollTarget: {
                type: String,
                default: 'scroll-target'
            },
            duration: {
                type: Number,
                default: 1000
            },
            easing: {
                type: String,
                default: 'easeInOutQuad'
            },
            offset: {
                type: Number,
                default: null
            }
        },
        methods: {
            scrollTo () {
                let target = this.$parent.$refs[this.scrollTarget]
                if( !target ) {
                    target = document.documentElement
                }

                Velocity(target, 'scroll', {
                    duration: this.duration,
                    easing: this.easing,
                    offset: this.offset
                })
            }
        }
    }
</script>

<style>
    .scroll-to {
        position: absolute;
        bottom: 30px;
        padding: 20px;
        left: 50%;
        transform: translateX(-50%);
        cursor: pointer;
    }
</style>

```

**Comment by drewbaker** [comment]
Updated the above code with a conditional around the Velocity scroll to not throw an error when the target is not found. Not sure if that is the "Vue" way, I'll leave that to you guys.

**Comment by drewbaker** [comment]
Made an update that allows you to pass an offset number and no target ref, which will then just scroll the window to that offset number. Useful for using with `$root.winHeight` to scroll one window height down.

**Comment by johndigital** [comment]
This hasn't been added yet has it? If not I'll do that today.

**Comment by SaFrMo** [comment]
Couple quick notes - 

* The `div` with the click event should be a `button` so that we don't have to add any extra click handlers for keyboards
* I've been using [scroll-to-element](https://www.npmjs.com/package/scroll-to-element) that does something very similar - implementation ends up looking like this:

```
// with a CSS selector
scrollToElement('header.site-header', {
  ease: 'inOutQuad',
  offset: // can pass optional raw px value here
})

// with a ref
scrollToElement(this.$refs.myRef.$el, { ease: 'inOutQuad' })
```

Might be more lightweight than making a full fh-component. Just wanted to throw that out there!

**Comment by SaFrMo** [comment]
@johndigital @drewbaker What's the status on this?

**Comment by johndigital** [comment]
I was thinking about this, I think it will be worth adding it using the scroll-to-element package you mentioned @SaFrMo. Since that package is small it should be okay to include in a fh-component, and if done right it should eliminate the need to every use that package in a theme.

It might seems a little overkill for such a small function, but it will be nice to never have to write out the JS for it again. I will plan to add this in.

**Comment by johndigital** [comment]
This has been added and documented in 9d65e32f4e3a6da549843fe7048fc11be90b1760

Documentation here: https://github.com/funkhaus/fh-components#scroll-to
