### ISSUE TITLE
WP Menu has no classes on it when viewing a blog post

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#51]
When viewing a blog post, I want the news "home page" to have an active color on it. Sometimes that could also be a category.

![screen shot 2018-04-06 at 3 34 24 pm](https://user-images.githubusercontent.com/475015/38447008-030358c8-39b0-11e8-84c0-e6abc06664d0.png)

I know there is a lot of issues with knowing when a blog post is being seen, so maybe at the very least we could just give each menu item a class with the menu item id and the developer id in it so we could hard code it?. I was thinking something like this: `menu-item menu-item-{menu_id} menu-item-{developer_id}`.

**Comment by johndigital** [comment]
This is now implemented, see some more discussion about it here: https://github.com/funkhaus/fh-components/issues/53

Getting the dev ID in a class requires both the latest version of fh-components and this [rest easy filter](https://github.com/funkhaus/vuepress/blob/master/functions/rest-easy-filters.php#L13-L28) which is now in vuepress by default (because Dev IDs are a vuepress only thing, it didn't make sense to add this logic to rest easy.)

The [latest version of Rest Easy](54db400931b958a8cc7044eb1bf213ebca19a2d1) now also adds a class indicating which nav item is the blog page, which should help solve this particular scenario.
