### ISSUE TITLE
Add Bool type to video-src prop

### ISSUE THREAD

**Issue by lwaldner** [funkhaus/fh-components#78]
Allow for a boolean to be passed into the video-src prop on responsive image

**Comment by johndigital** [comment]
This is now implemented in fc49c0f7aae0539c8c290f5be4406a33f59b463b, but actually causes another problem. Since html attributes are meant to read an exclusion as a boolean value, allowing booleans for this prop will make its value _always_ `false`, even when the attribute is just excluded rather than explicitly set.

To deal with this I've now made it so that `null` should be used when explicitly disabling the video feature. Like this: `<responsive-image :video-src="null" />`
