### ISSUE TITLE
Fix responsive-image to work if empty param passed in for attcahment object

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/fh-components#9]
Currently, if I do this:
```
var company = '';
<responsive-image :object="company" size="medium-thumb"/>
```

Responsive-image will throw an error and break the site. It should fail nicely if the attachment object is loosely equal to empty.

**Comment by johndigital** [comment]
@drewbaker @SaFrMo I went to go fix this, but now that I'm looking at it I wonder if the current setup is expected behavior. 

Currently, it would only throw an error if the value passed to `object` is **not** of the type object. The error is a validation error. The [Vue styleguide](https://vuejs.org/v2/style-guide/#Prop-definitions-essential) has a fairly strong opinion that all props should have validation that's as detailed as possible, so I think allowing `object` to be any value at all is going to be a bad practice.

The real solution here is to only render the component if you actually have the object data that you expect to:

`<responsive-image v-if="company" :object="company" />`

Thoughts?

**Comment by drewbaker** [comment]
The thing is, if I use this in a loop of featured thumbnails, and some aren’t set in the CMS, it will throw an error (empty string). So every time you use this component you will have to do a _get() just to deal with that scenario. It seems easier to just have the component not break if given an empty string.

**Comment by johndigital** [comment]
I don't think I'm understanding your use case. Could you post a snippet?

**Comment by drewbaker** [comment]
Like this:

```
<router-link :to="company.relativePath" class="company-block" v-for="(company, i) in companies">
    <responsive-image :object="company.featuredAttachment" size="medium-thumb"/>
</router-link>
```

**Comment by johndigital** [comment]
Is there any reason why this wouldn't work for you?
```
<router-link :to="company.relativePath" class="company-block" v-for="(company, i) in companies">
    <responsive-image v-if="company.featuredAttachment" :object="company.featuredAttachment" size="medium-thumb"/>
</router-link>
```

**Comment by drewbaker** [comment]
Yeah that would work, but I guess I'm a little confused on our general philosophy of Vue and components. Shouldn't we be making them to require the general smallest amount of code to be used? 

Handling an empty string in the component saves me from having to write `v-if="company.featuredAttachment"` every time I use `responsive-image`. If I don't write that if-statement, the way we build sites with WordPress, it's possible to break the entire site really easily. 

And the reason we don't want to handle this error is because it's a Vue convention? I respect that, but is it possible for it to not just break the site then? Like maybe build the markup and have text that says "you must set a featured image here" or something? That would actually be a useful feature on all sites.

**Comment by johndigital** [comment]
Yea, it makes sense to have the least amount of code possible, but in this scenario what are you expecting to happen when you pass in an empty string? Render an invisible image? Maybe just not render the component at all? I think it makes more sense to be more explicit about your intention outside the component, rather than trusting the black magic within the component to make that decision for you.

Maybe it would make sense to add some extra awareness to the component, if it doesn't have enough info to render an image at all then it might just set itself to display none and continue to log the non-critical error to the console so you're still prompted to deal with it properly.

**Comment by drewbaker** [comment]
Yeah, I think you are right about it being explicit about what is happening rather than just doing nothing. I think having it render a box with text saying "you must set an image for this post/page" or something would be a good idea for how we build sites. I wonder if it should render a placeholder image using something like placeholder.com?

**Comment by drewbaker** [comment]
![screen shot 2017-12-08 at 2 17 35 pm](https://user-images.githubusercontent.com/475015/33787561-a38210f0-dc22-11e7-8fb4-566043dc6bbf.png)

This is what it does currently if you pass in an empty object. It should probably not set a src attr at all, and just fallback to `<img alt="alt text in here">` if we were being legit to the spec. Not sure if we should do that. Maybe we put the `img` tag in, and if no src and no alt text, fallback to `<img alt="No image set">`

**Comment by johndigital** [comment]
Perfect, assigning to myself to get that implemented!
